Bypass shape seg
Lomolisso/geology-quantifier pull request #19
Opened 2022-10-26 14:28 UTC by Riul1999

# Bypass shape segmentation
Now we can get results directly from color segmentation, the `Segmentar` button works exactly as before.

## Changes

### `src/gui.py`
- Added buttons `Analizar` and `Segmentar` to get the results from a color segmentation and for perform a shape segmentation respectively.
- Added method analyze binded to `Analizar`  button, this method get all the shapes in the image and calcule the stadistics assuming all are in the same group. With this results we fiiled the table.
- Changed the results table view, now only shows the non-empty groups.
- For the results using directly the color segmentation image, we display a default color (Cyan).

### `src/shape_detection.py`
- Added default color (Cyan).
- Changed cluster_segmentation function to get the colors of the rectangles you want to use.

2022-10-27 21:46 UTC, fossesv17 requested changes
The feature itself is working fine but there are some conflicts to solve before merging.

2022-11-07 20:12 UTC, Riul1999 commented
> The feature itself is working fine but there are some conflicts to solve before merging.

ready

2022-11-08 13:45 UTC, fossesv17 approved these changes
Works great!

2022-11-09 23:28 UTC, EricContrerasP approved these changes

2022-11-10 05:03 UTC, merged